### PR TITLE
Adding empty screens and fixes url when selecting a server

### LINKED ISSUE #26: Empty screens and fixes
Need to add empty state screens for all friends pages (all/online/blocked/pending)

Need to fix comments from #24 :
- remove unnecessary comments and commented code
- fix url when selecting a server

### PR DESCRIPTION
**Pull request by NKateryna**

### CODE REVIEW

File: src/common/components/WrapperContents/index.js [hunk 1]
```diff
@@ -31,12 +31,14 @@ function WrapperContents({ children }) {
 
   function onClickServer(a) {
     return () => {
-      navigate(`channels/ + ${a._id}`);
+      console.log(a._id);
```
Comment (RuFi2k) [inline src/common/components/WrapperContents/index.js]: Remove console.log

File: src/common/components/WrapperContents/index.js [hunk 2]
```diff
@@ -31,12 +31,14 @@ function WrapperContents({ children }) {
...
+      navigate(`channels/${a._id}`);
       dispatch(saveActiveItem(a._id));
     };
   }
   function onClickMenuItem(a) {
```
Comment (RuFi2k) [inline src/common/components/WrapperContents/index.js]: Use better naming

**Review by RuFi2k — CHANGES_REQUESTED** [review]

File: .vscode/settings.json [hunk 3]
```diff
@@ -0,0 +1,3 @@
+{
+    "editor.defaultFormatter": "esbenp.prettier-vscode"
+}
```
Comment (RuFi2k) [inline .vscode/settings.json]: Add .vscode to gitignore file

**Review by RuFi2k — APPROVED** [review]

File: src/common/components/FriendsPagesSwitcher/index.js [hunk 4]
```diff
@@ -9,7 +9,7 @@ import {
 } from '../../../pages/friends';
 
 function FriendsPagesSwitcher() {
-  const [value, setValue] = useContext(FriendsPagesContext);
+  const [value, _] = useContext(FriendsPagesContext);
```
Comment (RuFi2k) [inline src/common/components/FriendsPagesSwitcher/index.js]: dont need to decompose the second value
`const [value] = useContext(FriendsPagesContext);`

**Review by RuFi2k — APPROVED** [review]
