### PR TITLE
Integrate join and leave server enproints. Bug fixing.

### LINKED ISSUE #39: Integrate join and leave server enproints
User should be available to join server from the explore list by clicking on it. After joining the list of servers in the sidebar should be updated, and user should be redirected to the new server.

To leave server, user should press arrow icon on the server screen and select "leave server" option. After that user need to confirm leaving from the server, list on sidebar should be updated and user should be navigated to the root friendlist screen.

API details:
```
    /**
       * POST /servers/:serverId
       * Join to the new server
       * headers: {
       *     Authorization: Bearer <authToken>
       * }
       *
       * parameters: {
       *     serverId: URL, required
       * }
       *
       * response: N/A
       * successCode: 204
       */
```

```
      /**
       * DELETE /servers/:serverId
       * Leave the server
       * headers: {
       *     Authorization: Bearer <authToken>
       * }
       *
       * parameters: {
       *     serverId: URL, required
       * }
       *
       * response: N/A
       * successCode: 204
       */
```

### PR DESCRIPTION
**Pull request by NKateryna**

### CODE REVIEW

File: src/common/components/FriendsEmpty/index.js [hunk 1]
```diff
@@ -15,15 +15,15 @@ const useStyles = makeStyles({
...
-      backgroundColor: 'var(--brend-color-hover)',
+      backgroundColor: 'var(--brand-color-hover)',
       color: 'var(--white)',
     },
     '&.Mui-disabled': {
-      background: 'var(--brend-color)',
+      background: 'var(--brand-color)',
       opacity: '0.5',
       color: 'var(--white)',
     },
```
Comment (RuFi2k) [inline src/common/components/FriendsEmpty/index.js:29]: fix linter warning

**Review by RuFi2k — APPROVED** [review]
